### ISSUE TITLE
头像上传失败

### ISSUE THREAD

**Issue by jaxvanyang** [WebChatting/chatting-vue#24]
生产环境，WS URL 貌似是写死到 localhost 了，头像上传失败应该可以在生产环境里复现。

![image](https://user-images.githubusercontent.com/25650612/226152639-72ef3901-b7d4-40d8-8699-de13e3b9edb1.png)

**Comment by Crazyokd** [comment]
ws路径确实是bug，但不是这个问题的根源。

测试发现后端接收到了响应，不过响应失败了，是后端问题。

**Comment by Crazyokd** [comment]
ws路径已修复，见 a5dae968f93e4b71f0c681391bcf205d7b910e93

**Comment by Crazyokd** [comment]
动态识别系统环境，从而选择相应的windows路径或linux路径

**Comment by Crazyokd** [comment]
https://github.com/WebChatting/chatting/pull/88

**Comment by Crazyokd** [comment]
[4b73b7e02d5b39a7313b7db5600b0faeebac27eb](https://github.com/WebChatting/chatting/commit/4b73b7e02d5b39a7313b7db5600b0faeebac27eb)
